# Generated by Django 5.0 on 2023-12-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0002_alter_day_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
