# Generated by Django 5.0 on 2023-12-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0003_day_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
